# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20160204_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailfield',
            name='value',
            field=models.TextField(),
        ),
    ]
