# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailfield',
            name='is_json',
            field=models.BooleanField(default=False),
        ),
    ]
